---
# Changes here will be overwritten by Copier
_commit: v2.67.3-31-g79487d0
_src_path: gh:remerge/template
is_golang_library: true
project_id: go-tools
project_license: private
project_name: Go Tools
project_owner: core
project_type: default
use_ansible: false
use_consul: false
use_golang: true
use_nodejs: false
use_nomad: false
use_python: false
use_ruby: false
use_terraform: false
