---
# Changes here will be overwritten by Copier
_commit: v2.4.4
_src_path: gh:remerge/template
is_golang_library: true
project_id: go-tools
project_license: private
project_name: Go Tools
project_owner: core
project_type: default
run_workflows_for_all_branches: false
use_ansible: false
use_consul: false
use_golang: true
use_nomad: false
use_python: false
use_terraform: false
