package normalize

import "strings"

// CountryAlpha2 returns the ISO-3166-1 alpha 2 code for a given
// alpha 2, 3 or longer name. If not found "xx" is returned
func CountryAlpha2(country string) string {
	if country == "" {
		return "xx"
	}

	c := strings.ToLower(country)

	if len(c) == 2 {
		return c
	}

	if len(c) == 3 {
		if match, ok := countries[c]; ok {
			return match
		}
	}

	if match, ok := countriesNonStandard[c]; ok {
		return match
	}

	return "xx"
}

var countries = map[string]string{
	"and": "ad",
	"are": "ae",
	"afg": "af",
	"atg": "ag",
	"aia": "ai",
	"alb": "al",
	"arm": "am",
	"ago": "ao",
	"ata": "aq",
	"arg": "ar",
	"asm": "as",
	"aut": "at",
	"aus": "au",
	"abw": "aw",
	"ala": "ax",
	"aze": "az",
	"bih": "ba",
	"brb": "bb",
	"bgd": "bd",
	"bel": "be",
	"bfa": "bf",
	"bgr": "bg",
	"bhr": "bh",
	"bdi": "bi",
	"ben": "bj",
	"blm": "bl",
	"bmu": "bm",
	"brn": "bn",
	"bol": "bo",
	"bes": "bq",
	"bra": "br",
	"bhs": "bs",
	"btn": "bt",
	"bvt": "bv",
	"bwa": "bw",
	"blr": "by",
	"blz": "bz",
	"can": "ca",
	"cck": "cc",
	"cod": "cd",
	"caf": "cf",
	"cog": "cg",
	"che": "ch",
	"civ": "ci",
	"cok": "ck",
	"chl": "cl",
	"cmr": "cm",
	"chn": "cn",
	"col": "co",
	"cri": "cr",
	"cub": "cu",
	"cpv": "cv",
	"cuw": "cw",
	"cxr": "cx",
	"cyp": "cy",
	"cze": "cz",
	"deu": "de",
	"dji": "dj",
	"dnk": "dk",
	"dma": "dm",
	"dom": "do",
	"dza": "dz",
	"ecu": "ec",
	"est": "ee",
	"egy": "eg",
	"esh": "eh",
	"eri": "er",
	"esp": "es",
	"eth": "et",
	"fin": "fi",
	"fji": "fj",
	"flk": "fk",
	"fsm": "fm",
	"fro": "fo",
	"fra": "fr",
	"gab": "ga",
	"gbr": "gb",
	"grd": "gd",
	"geo": "ge",
	"guf": "gf",
	"ggy": "gg",
	"gha": "gh",
	"gib": "gi",
	"grl": "gl",
	"gmb": "gm",
	"gin": "gn",
	"glp": "gp",
	"gnq": "gq",
	"grc": "gr",
	"sgs": "gs",
	"gtm": "gt",
	"gum": "gu",
	"gnb": "gw",
	"guy": "gy",
	"hkg": "hk",
	"hmd": "hm",
	"hnd": "hn",
	"hrv": "hr",
	"hti": "ht",
	"hun": "hu",
	"idn": "id",
	"irl": "ie",
	"isr": "il",
	"imn": "im",
	"ind": "in",
	"iot": "io",
	"irq": "iq",
	"irn": "ir",
	"isl": "is",
	"ita": "it",
	"jey": "je",
	"jam": "jm",
	"jor": "jo",
	"jpn": "jp",
	"ken": "ke",
	"kgz": "kg",
	"khm": "kh",
	"kir": "ki",
	"com": "km",
	"kna": "kn",
	"prk": "kp",
	"kor": "kr",
	"xkx": "xk",
	"kwt": "kw",
	"cym": "ky",
	"kaz": "kz",
	"lao": "la",
	"lbn": "lb",
	"lca": "lc",
	"lie": "li",
	"lka": "lk",
	"lbr": "lr",
	"lso": "ls",
	"ltu": "lt",
	"lux": "lu",
	"lva": "lv",
	"lby": "ly",
	"mar": "ma",
	"mco": "mc",
	"mda": "md",
	"mne": "me",
	"maf": "mf",
	"mdg": "mg",
	"mhl": "mh",
	"mkd": "mk",
	"mli": "ml",
	"mmr": "mm",
	"mng": "mn",
	"mac": "mo",
	"mnp": "mp",
	"mtq": "mq",
	"mrt": "mr",
	"msr": "ms",
	"mlt": "mt",
	"mus": "mu",
	"mdv": "mv",
	"mwi": "mw",
	"mex": "mx",
	"mys": "my",
	"moz": "mz",
	"nam": "na",
	"ncl": "nc",
	"ner": "ne",
	"nfk": "nf",
	"nga": "ng",
	"nic": "ni",
	"nld": "nl",
	"nor": "no",
	"npl": "np",
	"nru": "nr",
	"niu": "nu",
	"nzl": "nz",
	"omn": "om",
	"pan": "pa",
	"per": "pe",
	"pyf": "pf",
	"png": "pg",
	"phl": "ph",
	"pak": "pk",
	"pol": "pl",
	"spm": "pm",
	"pcn": "pn",
	"pri": "pr",
	"pse": "ps",
	"prt": "pt",
	"plw": "pw",
	"pry": "py",
	"qat": "qa",
	"reu": "re",
	"rou": "ro",
	"srb": "rs",
	"rus": "ru",
	"rwa": "rw",
	"sau": "sa",
	"slb": "sb",
	"syc": "sc",
	"sdn": "sd",
	"ssd": "ss",
	"swe": "se",
	"sgp": "sg",
	"shn": "sh",
	"svn": "si",
	"sjm": "sj",
	"svk": "sk",
	"sle": "sl",
	"smr": "sm",
	"sen": "sn",
	"som": "so",
	"sur": "sr",
	"stp": "st",
	"slv": "sv",
	"sxm": "sx",
	"syr": "sy",
	"swz": "sz",
	"tca": "tc",
	"tcd": "td",
	"atf": "tf",
	"tgo": "tg",
	"tha": "th",
	"tjk": "tj",
	"tkl": "tk",
	"tls": "tl",
	"tkm": "tm",
	"tun": "tn",
	"ton": "to",
	"tur": "tr",
	"tto": "tt",
	"tuv": "tv",
	"twn": "tw",
	"tza": "tz",
	"ukr": "ua",
	"uga": "ug",
	"umi": "um",
	"usa": "us",
	"ury": "uy",
	"uzb": "uz",
	"vat": "va",
	"vct": "vc",
	"ven": "ve",
	"vgb": "vg",
	"vir": "vi",
	"vnm": "vn",
	"vut": "vu",
	"wlf": "wf",
	"wsm": "ws",
	"yem": "ye",
	"myt": "yt",
	"zaf": "za",
	"zmb": "zm",
	"zwe": "zw",
	"scg": "cs",
	"ant": "an",
}

// non-standardised names some with misspellings
var countriesNonStandard = map[string]string{
	"afghanistan":                         "af",
	"albania":                             "al",
	"algeria":                             "dz",
	"american samoa":                      "as",
	"andorra":                             "ad",
	"angola":                              "ao",
	"anguilla":                            "ai",
	"antarctica":                          "aq",
	"antigua and barbuda":                 "ag",
	"argentina":                           "ar",
	"armenia":                             "am",
	"aruba":                               "aw",
	"ascension and tristan da cunha":      "sh",
	"australia":                           "au",
	"austria":                             "at",
	"azerbaijan":                          "az",
	"bahamas":                             "bs",
	"bahrain":                             "bh",
	"bangladesh":                          "bd",
	"barbados":                            "bb",
	"belarus":                             "by",
	"belgium":                             "be",
	"belize":                              "bz",
	"benin":                               "bj",
	"bermuda":                             "bm",
	"bhutan":                              "bt",
	"bolivia":                             "bo",
	"bosnia and herzegovina":              "ba",
	"botswana":                            "bw",
	"bouvet island":                       "bv",
	"brazil":                              "br",
	"british antarctic territory":         "bq",
	"british indian ocean territory":      "io",
	"british virgin islands":              "vg",
	"brunei":                              "bn",
	"bulgaria":                            "bg",
	"burkina faso":                        "bf",
	"burundi":                             "bi",
	"cambodia":                            "kh",
	"cameroon":                            "cm",
	"canada":                              "ca",
	"canton and enderbury islands":        "ct",
	"cape verde":                          "cv",
	"cayman islands":                      "ky",
	"central african republic":            "cf",
	"chad":                                "td",
	"chile":                               "cl",
	"china":                               "cn",
	"christmas island":                    "cx",
	"cocos (keeling) islands":             "cc",
	"cocos [keeling] islands":             "cc",
	"colombia":                            "co",
	"comoros":                             "km",
	"congo - brazzaville":                 "cg",
	"congo - kinshasa":                    "cd",
	"cook islands":                        "ck",
	"costa rica":                          "cr",
	"cote d'ivoire":                       "ci",
	"croatia":                             "hr",
	"cuba":                                "cu",
	"cyprus":                              "cy",
	"czech republic":                      "cz",
	"czechia":                             "cz",
	"côte d’ivoire":                       "ci",
	"democratic republic of the congo":    "cd",
	"denmark":                             "dk",
	"djibouti":                            "dj",
	"dominica":                            "dm",
	"dominican republic":                  "do",
	"dronning maud land":                  "nq",
	"east germany":                        "dd",
	"ecuador":                             "ec",
	"egypt":                               "eg",
	"el salvador":                         "sv",
	"equatorial guinea":                   "gq",
	"eritrea":                             "er",
	"estonia":                             "ee",
	"ethiopia":                            "et",
	"falkland islands (islas malvinas)":   "fk",
	"falkland islands":                    "fk",
	"faroe islands":                       "fo",
	"federated states of micronesia":      "fm",
	"fiji":                                "fj",
	"finland":                             "fi",
	"france":                              "fr",
	"french guiana":                       "gf",
	"french polynesia":                    "pf",
	"french southern and antarctic lands": "tf",
	"french southern and antarctic territories": "fq",
	"french southern territories":               "tf",
	"gabon":                                     "ga",
	"gambia":                                    "gm",
	"georgia":                                   "ge",
	"germany ":                                  "de",
	"germany":                                   "de",
	"ghana":                                     "gh",
	"gibraltar":                                 "gi",
	"greece":                                    "gr",
	"greenland":                                 "gl",
	"grenada":                                   "gd",
	"guadeloupe":                                "gp",
	"guam":                                      "gu",
	"guatemala":                                 "gt",
	"guernsey":                                  "gg",
	"guinea":                                    "gn",
	"guinea-bissau":                             "gw",
	"guyana":                                    "gy",
	"haiti":                                     "ht",
	"heard island and mcdonald islands":         "hm",
	"honduras":                                  "hn",
	"hong kong sar china":                       "hk",
	"hong kong":                                 "hk",
	"hungary":                                   "hu",
	"iceland":                                   "is",
	"india":                                     "in",
	"indonesia":                                 "id",
	"iran":                                      "ir",
	"iraq":                                      "iq",
	"ireland":                                   "ie",
	"isle of man":                               "im",
	"israel":                                    "il",
	"italy":                                     "it",
	"jamaica":                                   "jm",
	"japan":                                     "jp",
	"jersey":                                    "je",
	"johnston island":                           "jt",
	"jordan":                                    "jo",
	"kazakhstan":                                "kz",
	"kenya":                                     "ke",
	"kiribati":                                  "ki",
	"kosovo":                                    "xk",
	"kuwait":                                    "kw",
	"kyrgyzstan":                                "kg",
	"laos":                                      "la",
	"latvia":                                    "lv",
	"lebanon":                                   "lb",
	"lesotho":                                   "ls",
	"liberia":                                   "lr",
	"libya":                                     "ly",
	"liechtenstein":                             "li",
	"lithuania":                                 "lt",
	"luxembourg":                                "lu",
	"macau sar china":                           "mo",
	"macau":                                     "mo",
	"macedonia (fyrom)":                         "mk",
	"macedonia":                                 "mk",
	"madagascar":                                "mg",
	"malawi":                                    "mw",
	"malaysia":                                  "my",
	"maldives":                                  "mv",
	"mali":                                      "ml",
	"malta":                                     "mt",
	"marshall islands":                          "mh",
	"martinique":                                "mq",
	"mauritania":                                "mr",
	"mauritius":                                 "mu",
	"mayotte":                                   "yt",
	"metropolitan france":                       "fx",
	"mexico":                                    "mx",
	"micronesia":                                "fm",
	"midway islands":                            "mi",
	"moldova":                                   "md",
	"monaco":                                    "mc",
	"mongolia":                                  "mn",
	"montenegro":                                "me",
	"montserrat":                                "ms",
	"morocco":                                   "ma",
	"mozambique":                                "mz",
	"myanmar (burma)":                           "mm",
	"myanmar [burma]":                           "mm",
	"namibia":                                   "na",
	"nauru":                                     "nr",
	"nepal":                                     "np",
	"netherlands antilles":                      "an",
	"netherlands":                               "nl",
	"neutral zone":                              "nt",
	"new caledonia":                             "nc",
	"new zealand":                               "nz",
	"nicaragua":                                 "ni",
	"niger":                                     "ne",
	"nigeria":                                   "ng",
	"niue":                                      "nu",
	"norfolk island":                            "nf",
	"north korea":                               "kp",
	"north vietnam":                             "vd",
	"northern mariana islands":                  "mp",
	"norway":                                    "no",
	"oman":                                      "om",
	"pacific islands trust territory":           "pc",
	"pakistan":                                  "pk",
	"palau":                                     "pw",
	"palestine":                                 "ps",
	"palestinian territories":                   "ps",
	"panama canal zone":                         "pz",
	"panama":                                    "pa",
	"papua new guinea":                          "pg",
	"paraguay":                                  "py",
	"people's democratic republic of yemen":     "yd",
	"peru":                                      "pe",
	"philippines":                               "ph",
	"pitcairn islands":                          "pn",
	"poland":                                    "pl",
	"portugal":                                  "pt",
	"puerto rico":                               "pr",
	"qatar":                                     "qa",
	"reggio emilia province":                    "it",
	"republic of the congo":                     "cg",
	"reunion":                                   "re",
	"romania":                                   "ro",
	"russia":                                    "ru",
	"rwanda":                                    "rw",
	"réunion":                                   "re",
	"saint barthélemy":                          "bl",
	"saint helena":                              "sh",
	"saint kitts and nevis":                     "kn",
	"saint lucia":                               "lc",
	"saint martin":                              "mf",
	"saint pierre and miquelon":                 "pm",
	"saint vincent and the grenadines":          "vc",
	"samoa":                                     "ws",
	"san marino":                                "sm",
	"sao tome and principe":                     "st",
	"saudi arabia":                              "sa",
	"senegal":                                   "sn",
	"serbia and montenegro":                     "cs",
	"serbia":                                    "rs",
	"seychelles":                                "sc",
	"sierra leone":                              "sl",
	"singapore":                                 "sg",
	"slovakia":                                  "sk",
	"slovenia":                                  "si",
	"solomon islands":                           "sb",
	"somalia":                                   "so",
	"south africa":                              "za",
	"south georgia and the south sandwich islands": "gs",
	"south korea":                          "kr",
	"spain":                                "es",
	"sri lanka":                            "lk",
	"sudan":                                "sd",
	"suriname":                             "sr",
	"svalbard and jan mayen":               "sj",
	"swaziland":                            "sz",
	"sweden":                               "se",
	"switzerland":                          "ch",
	"syria":                                "sy",
	"são tomé and príncipe":                "st",
	"taiwan":                               "tw",
	"tajikistan":                           "tj",
	"tanzania":                             "tz",
	"thailand":                             "th",
	"the bahamas":                          "bs",
	"the gambia":                           "gm",
	"timor-leste":                          "tl",
	"togo":                                 "tg",
	"tokelau":                              "tk",
	"tonga":                                "to",
	"trinidad and tobago":                  "tt",
	"tunisia":                              "tn",
	"turkey":                               "tr",
	"turkmenistan":                         "tm",
	"turks and caicos islands":             "tc",
	"tuvalu":                               "tv",
	"u.s. minor outlying islands":          "um",
	"u.s. miscellaneous pacific islands":   "pu",
	"u.s. virgin islands":                  "vi",
	"uganda":                               "ug",
	"ukraine":                              "ua",
	"union of soviet socialist republics":  "su",
	"united arab emirates":                 "ae",
	"united kingdom":                       "gb",
	"united states ":                       "us",
	"united states minor outlying islands": "um",
	"united states":                        "us",
	"unknown or invalid region":            "zz",
	"uruguay":                              "uy",
	"uzbekistan":                           "uz",
	"vanuatu":                              "vu",
	"vatican city":                         "va",
	"venezuela":                            "ve",
	"vietnam":                              "vn",
	"wake island":                          "wk",
	"wallis and futuna":                    "wf",
	"western sahara":                       "eh",
	"yemen":                                "ye",
	"zambia":                               "zm",
	"zimbabwe":                             "zw",
	"åland islands":                        "ax",
}
