package normalize

import "strings"

// Currency check the given code against the ISO 4217 and returns
// the uppercase version if it is valid. It returns EUR if € is passed and
// USD if $ is passed as an argument. All other cases return the given fallback value.
func Currency(given, fallback string) string {
	if given == "" {
		return fallback
	}
	if given == "$" {
		return "USD"
	}
	if given == "€" {
		return "EUR"
	}
	if len(given) != 3 {
		return fallback
	}
	upper := strings.ToUpper(given)
	if _, found := validCurrencies[upper]; found {
		return upper
	}
	return fallback
}

type 空 struct{} // an empty japanese struct ;-)

var validCurrencies = map[string]空{
	"AFN": 空{},
	"ALL": 空{},
	"AMD": 空{},
	"ANG": 空{},
	"AOA": 空{},
	"ARS": 空{},
	"AUD": 空{},
	"AWG": 空{},
	"AZN": 空{},
	"BAM": 空{},
	"BBD": 空{},
	"BDT": 空{},
	"BGN": 空{},
	"BHD": 空{},
	"BIF": 空{},
	"BMD": 空{},
	"BND": 空{},
	"BOB": 空{},
	"BOV": 空{},
	"BRL": 空{},
	"BSD": 空{},
	"BTN": 空{},
	"BWP": 空{},
	"BYR": 空{},
	"BZD": 空{},
	"CAD": 空{},
	"CDF": 空{},
	"CHE": 空{},
	"CHF": 空{},
	"CHW": 空{},
	"CLF": 空{},
	"CLP": 空{},
	"CNY": 空{},
	"COP": 空{},
	"COU": 空{},
	"CRC": 空{},
	"CUP": 空{},
	"CVE": 空{},
	"CYP": 空{},
	"CZK": 空{},
	"DJF": 空{},
	"DKK": 空{},
	"DOP": 空{},
	"DZD": 空{},
	"EEK": 空{},
	"EGP": 空{},
	"ERN": 空{},
	"ETB": 空{},
	"EUR": 空{},
	"FJD": 空{},
	"FKP": 空{},
	"GBP": 空{},
	"GEL": 空{},
	"GHS": 空{},
	"GIP": 空{},
	"GMD": 空{},
	"GNF": 空{},
	"GTQ": 空{},
	"GYD": 空{},
	"HKD": 空{},
	"HNL": 空{},
	"HRK": 空{},
	"HTG": 空{},
	"HUF": 空{},
	"IDR": 空{},
	"ILS": 空{},
	"INR": 空{},
	"IQD": 空{},
	"IRR": 空{},
	"ISK": 空{},
	"JMD": 空{},
	"JOD": 空{},
	"JPY": 空{},
	"KES": 空{},
	"KGS": 空{},
	"KHR": 空{},
	"KMF": 空{},
	"KPW": 空{},
	"KRW": 空{},
	"KWD": 空{},
	"KYD": 空{},
	"KZT": 空{},
	"LAK": 空{},
	"LBP": 空{},
	"LKR": 空{},
	"LRD": 空{},
	"LSL": 空{},
	"LTL": 空{},
	"LVL": 空{},
	"LYD": 空{},
	"MAD": 空{},
	"MDL": 空{},
	"MGA": 空{},
	"MKD": 空{},
	"MMK": 空{},
	"MNT": 空{},
	"MOP": 空{},
	"MRO": 空{},
	"MTL": 空{},
	"MUR": 空{},
	"MVR": 空{},
	"MWK": 空{},
	"MXN": 空{},
	"MXV": 空{},
	"MYR": 空{},
	"MZN": 空{},
	"NAD": 空{},
	"NGN": 空{},
	"NIO": 空{},
	"NOK": 空{},
	"NPR": 空{},
	"NZD": 空{},
	"OMR": 空{},
	"PAB": 空{},
	"PEN": 空{},
	"PGK": 空{},
	"PHP": 空{},
	"PKR": 空{},
	"PLN": 空{},
	"PYG": 空{},
	"QAR": 空{},
	"RON": 空{},
	"RSD": 空{},
	"RUB": 空{},
	"RWF": 空{},
	"SAR": 空{},
	"SBD": 空{},
	"SCR": 空{},
	"SDG": 空{},
	"SEK": 空{},
	"SGD": 空{},
	"SHP": 空{},
	"SKK": 空{},
	"SLL": 空{},
	"SOS": 空{},
	"SRD": 空{},
	"STD": 空{},
	"SYP": 空{},
	"SZL": 空{},
	"THB": 空{},
	"TJS": 空{},
	"TMM": 空{},
	"TND": 空{},
	"TOP": 空{},
	"TRY": 空{},
	"TTD": 空{},
	"TWD": 空{},
	"TZS": 空{},
	"UAH": 空{},
	"UGX": 空{},
	"USD": 空{},
	"XAF": 空{},
	"XAG": 空{},
	"XAU": 空{},
	"XCD": 空{},
	"XPT": 空{},
	"XXX": 空{},
}
