name: Go App
on:
  pull_request:
  push:
    branches:
    - master
    - main
    - production

jobs:
  go-checks:
    uses: remerge/workflows/.github/workflows/go-checks.yml@main
    secrets:
      ssh_key: ${{ secrets.DEPLOY_USER_SSH_KEY }}
  go-build:
    uses: remerge/workflows/.github/workflows/go-build.yml@main
    needs: [go-checks]
    secrets:
      ssh_key: ${{ secrets.DEPLOY_USER_SSH_KEY }}
  go-upload:
    uses: remerge/workflows/.github/workflows/go-upload-s3.yml@main
    needs: [go-build]
    with:
      artifact: ${{ needs.go-build.outputs.artifact }}
    secrets:
      aws_key_id: ${{ secrets.DEPLOYMENT_ARTIFACT_AWS_KEY_ID }}
      aws_key_secret: ${{ secrets.DEPLOYMENT_ARTIFACT_AWS_KEY_SECRET }}
