name: Go App
on:
  pull_request:
  push:
    branches:
    - master
    - main
    - production

jobs:
  go-checks:
    uses: remerge/workflows/.github/workflows/go-checks.yml@main
    secrets:
      ssh_key: ${{ secrets.DEPLOY_USER_SSH_KEY }}
