# Runs common checks for Go package: lint (fmt, modules, static, shadowing),
# tests and race.

name: Go checks

on:
  workflow_call:
    inputs:
      golang_version:
        type: string
        required: false
        default: ""
        description: "Override Golang version in go.mod"
      no-race:
        type: boolean
        required: false
        default: false
        description: "Run race detector"
      lint-target:
        type: string
        required: false
        default: 'lint'
        description: "Lint Make target"
      compose-file:
        type: string
        required: false
        default: docker-compose.yml
        description: "Docker-compose file to detect"
      compose-wait:
        type: number
        required: false
        default: 1
        description: "Seconds to wait after docker-compose initialised"
      no-compose:
        type: boolean
        required: false
        default: false
        description: "Do not run docker-compose even compose file is present"

jobs:
  go-test:
    name: "lint_and_test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "GO_VERSION=$(grep '^go ' < go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
    - name: go modules cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: ${{ runner.os }}-go-mod-${{ github.job }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-${{ github.job }}-
    - name: go tools cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/mkf/.tools
        key: ${{ runner.os }}-go-tools-${{ inputs.golang_version || env.GO_VERSION }}-${{ github.job }}
        restore-keys: |
          ${{ runner.os }}-go-tools-${{ inputs.golang_version || env.GO_VERSION }}-${{ github.job }}
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.golang_version || env.GO_VERSION }}

    - name: Update git config
      run: |
        git config --global url."https://${{secrets.GITHUB_TOKEN}}@github.com/".insteadOf https://github.com/

    - run: make ${{ inputs.lint-target }}
    - run: 'docker-compose -f "${{ inputs.compose-file }}" up -d --build && sleep ${{ inputs.compose-wait }}'
      if: "${{ !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"
    - run: make test-nocache
    - run: make race-nocache
      if: '!inputs.no-race'
    - run: 'docker-compose -f "${{ inputs.compose-file }}" down'
      if: "${{ always() && !inputs.no-compose && hashFiles(inputs.compose-file) != '' }}"
